services:
  postgres:
    image: postgres:15-alpine
    container_name: visiobin-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: visiobin
    ports:
      - "5433:5432"
    volumes:
      - visiobin_pgdata:/var/lib/postgresql/data
      - ./backend/migrations/001_init.sql:/docker-entrypoint-initdb.d/001_init.sql
      - ./backend/migrations/002_maintenance_logs.sql:/docker-entrypoint-initdb.d/002_maintenance_logs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: visiobin-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/visiobin?sslmode=disable
      - JWT_SECRET=visiobin_super_secret_key_2024
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/firebase-service-account.json
    volumes:
      - ./backend/.env:/app/.env:ro
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  dashboard:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    container_name: visiobin-dashboard
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - backend

  simulator:
    build:
      context: ./iot-simulator
      dockerfile: Dockerfile
    container_name: visiobin-simulator
    restart: unless-stopped
    depends_on:
      - backend
    command: ["-url", "http://backend:8080/api/v1", "-interval", "5", "-user", "ibnu", "-pass", "zee343212"]

  adminer:
    image: adminer
    container_name: visiobin-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  visiobin_pgdata:
